### ISSUE TITLE
Build acsql database

### ISSUE THREAD

**Issue by bourque** [bourque/acsql#1]
I need to develop a (normalized) schema for the ascql database.  The main purpose of this database is to store image header data of every observation as well as basic filesystem information.

**Comment by bourque** [comment]
Some ideas from meeting with @saraogaz:

What to index on:
+ Aperture

Useful functions:
+ Print out `trl` information for given file.

Possible custom data structures:
+ association

**Comment by SaraOgaz** [comment]
acs postflash started Jan 2015, so we should take 2014+2015 data.

**Comment by bourque** [comment]
A working version of `database_interface.py` has been added per 8f99c60239b71430169ce8617ef310109aaea683
